language: php

php:
    - 7.1

before_script:
    # Install composer
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install

script:
    - ./bin/phpmetrics src
    - ./bin/phpcs --standard=vendor/escapestudios/symfony2-coding-standard/Symfony/ src/
    - ./bin/phpcs --standard=tests/phpcs-ruleset.xml tests/
    - ./bin/phpunit
